name: Build

on:
  push:
    branches: [ master ]

# cancel previous workflows, run only one workflow
concurrency:
  #group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: install dependencies
      run: npm i -g gulp-cli typescript npm ts-node && npm install
      continue-on-error: true
      id: install
    - if: steps.install.outcome == 'failure'
      shell: bash
      name: clean install
      run: |
        # rm -rf package-lock.json
        # rm -rf node_modules
        npm update @types/through2 cross-spawn nodejs-package-types tui-jsdoc-template

    - name: Build
      run: npm run build 

    - name: Re-deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: master # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        force: false # merge instead delete old files
