name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm i -g gulp-cli typescript npm ts-node && npm install

    - name: Build
      run: npm run build

    - name: Re-deploy 🚀
      uses: JamesIves/github-pages-deploy-action
      with:
        branch: master # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        force: false
