name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install dependencies
      run: npm i -g gulp-cli typescript npm ts-node && npm install

    - name: Build
      run: npm run build

    - name: Re-deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: master # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        force: false
